# Name of the project. Required, but used only for reference.
name = "CHONK"
# Target filename. Required.
output = "Final_Fantasy_5_Advance (modified).gba"
# Target platform. Required.
system = "gba"
# Image compression format. Default: 'none'
compress = "lz77"

# image configuration; per-image keys override this.
# How big the pointer is, in bits.
graphic_size = 24
# Target format.
graphic_format  = "GBA-4BPP"
# How many colours are in the palette. This will issue an error if
# there are more colours than this.
palette_size = 16
# How the palette is stored.
palette_format = "RGBA5551"

# Images to be converted and inserted
[[image]]
# Name of the image. Required, but used only for reference.
name    = "CHONK(right)"
# Filename for the image.
filename    = "NeoExChonk1.png"
# Pointer to the image.
graphic = 0x131A00
# Palette location.
palette = 0x2140D4
# Where the graphic data itself should be stored. -1 means EOF.
target  = 0x900000

[[image]]
name    = "CHONK(left)"
filename    = "NeoExChonk2.png"
graphic = 0x131A08
palette = 0x214F10
target  = -1